# SSO Red Hat credentials
username: "yourusername"                           # without @redhat.com
pin: "yourpin"                                     # corresponding to the created token at token.redhat.com
secret: "4439be1a......................bc2d3ec263" # secret from the generated token

# Github credentials
github_username: ""
github_password: ""
