apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/part-of: snow-t1
  name: snow-t1
  namespace: lx-snow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: snow-t1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: snow-t1
        app.kubernetes.io/component: snow-t1
        app.kubernetes.io/name: snow-t1
        deploymentconfig: snow-t1
    spec:
      containers:
        - args:
            - /bin/sh
            - -c
            - id && snow -t 'RHT Learner Experience'
          env:
            - name: DISPLAY
              value: :99
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: T1_FRONTEND_OPENSHIFT_ROUTE
              value: https://t1-shifts-frontend-lx-snow.apps.tools-na100.dev.ole.redhat.com/
            - name: DEFAULT_LOCAL_TMP
              value: /tmp
          image: quay.io/carias_rh/lx-toolbox:latest
          imagePullPolicy: Always
          name: snow-t1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /runner
              name: snow-t1-1
            - mountPath: /app/lx-toolbox/playbooks/vars/credentials.yml
              name: credentials-volume
              subPath: credentials.yml
        - image: docker.io/metal3d/xvfb
          imagePullPolicy: Always
          name: xvfb
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir: {}
          name: snow-t1-1
        - name: credentials-volume
          secret:
            defaultMode: 420
            secretName: credentials
