apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: "false"
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/carias-rh/t1-shifts-main
    deployment.kubernetes.io/revision: "6"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"t1-shifts-frontend:latest","namespace":"lx-snow"},"fieldPath":"spec.template.spec.containers[?(@.name==\"t1-shifts-frontend\")].image","pause":"false"}]'
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: t1-shifts-frontend
    app.kubernetes.io/component: t1-shifts-frontend
    app.kubernetes.io/instance: t1-shifts-frontend
    app.kubernetes.io/name: t1-shifts-frontend
    app.kubernetes.io/part-of: snow-t1
  name: t1-shifts-frontend
  namespace: lx-snow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: t1-shifts-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: t1-shifts-frontend
        deploymentconfig: t1-shifts-frontend
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/lx-snow/t1-shifts-frontend@sha256:81c4d11c401cc749d39226e7317662bbc265fcd0ab0f6cb8457022de3d97141d
          imagePullPolicy: Always
          name: t1-shifts-frontend
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
