- name: ROL labs launcher
  hosts: localhost
  vars_files: credentials.yml
  vars:
    - lab_environment: rol-stage
    - course_id: 
        - do467-2.1
    - rh_username: "{{ username | default('') }}"
    - rh_password: "{{ password | default('') }}"
    - counter: 0
        
  tasks:
    - name: Generate selenium script
      template:
        src: templates/rol-lab-recreate.py.j2
        dest: "/tmp/recreate.py"

    - name: Recreate courses
      shell: '/usr/bin/python3 /tmp/recreate.py'
      register: selenium
