---
- name: SNOW Typos Checker
  hosts: localhost
  vars_files:
    - credentials.yml
  vars:
    rh_username: "{{ username | default('') }}"
    rh_password: "{{ password | default('') }}"
    teammate_name: 'Carlos Arias'
  tasks:
    - name: Generate SNOW Typos Checker script
      ansible.builtin.template:
        src: templates/snow-ai.py.j2
        dest: "/tmp/snow-ai.py"
        mode: '0755'
