- name: ROL labs launcher
  hosts: localhost
  vars_files: credentials.yml
  vars:
    - lab_environment: rol
    - rh_username: "{{ username | default('') }}"
    - rh_password: "{{ password | default('') }}"
    - counter: 0
        
  tasks:
    - name: Generate selenium script
      template:
        src: templates/rol-lab-start.py.j2
        dest: "/tmp/start.py"

    - name: Create courses
      shell: '/usr/bin/python3 /tmp/start.py'
      register: selenium
